rrbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  limb1_position_controller:
    type: effort_controllers/JointPositionController
    joint: rrbot__limb_joint_1
    pid: {p: 5.0, i: 0, d: 0.1}
  limb2_position_controller:
    type: effort_controllers/JointPositionController
    joint: rrbot__limb_joint_2
    pid: {p: 5.0, i: 0, d: 0.1}
  limb3_position_controller:
    type: effort_controllers/JointPositionController
    joint: rrbot__limb_joint_3
    pid: {p: 5.0, i: 0, d: 0.1}
  limb4_position_controller:
    type: effort_controllers/JointPositionController
    joint: rrbot__limb_joint_4
    pid: {p: 5.0, i: 0, d: 0.1}

  body1_position_controller:
    type: effort_controllers/JointPositionController
    joint: rrbot__body_joint_1
    pid: {p: 5.0, i: 0, d: 0.1}
  body2_position_controller:
    type: effort_controllers/JointPositionController
    joint: rrbot__body_joint_2
    pid: {p: 5.0, i: 0, d: 0.1}
  body3_position_controller:
    type: effort_controllers/JointPositionController
    joint: rrbot__body_joint_3
    pid: {p: 5.0, i: 0, d: 0.1}
  body4_position_controller:
    type: effort_controllers/JointPositionController
    joint: rrbot__body_joint_4
    pid: {p: 5.0, i: 0, d: 0.1}
  body5_position_controller:
    type: effort_controllers/JointPositionController
    joint: rrbot__body_joint_5
    pid: {p: 5.0, i: 0, d: 0.1}
  body6_position_controller:
    type: effort_controllers/JointPositionController
    joint: rrbot__body_joint_6
    pid: {p: 5.0, i: 0, d: 0.1}

